const data = {
  English: {
    home_title1: "Who is Jain Sadhu ?",
    home_title2: "How does Jain Sadhu look ?",
    home_title3: "Why do they take Diksha ?",
    home_title4: "Where does Jain Sadhu Live ?",
    home_title5: "What does Jain Sadhu eat ?",
    home_title6: "What is my duty ?",
    home_text1: "Who is Jain Sadhu ?",
    home_text2: "How does Jain Sadhu look ?",
    home_text3: "Why do they take Diksha ?",
    home_text4: "Where does Jain Sadhu <br>Live ?",
    home_text5: "What does Jain Sadhu eat ?",
    home_text6: "What is my<br>duty ?",
    banner_1_text_one: "A Boy after taking Diksha is called a Sadhu",
    banner_1_text_two: "A Girl after taking Diksha is called a Sadhvi",
    slide_1: "A Boy after taking Diksha is called a Sadhu",
    slide_2: "A Girl after taking Diksha is called a Sadhvi",
    banner_2_text_one: "They wear white clothes",
    banner_2_text_two: "They use Rajoharan (Ogha) to save small insects",
    banner_2_text_three: "They use Muhpatti while talking",
    slide_3: "They wear white clothes",
    slide_4: "They use Rajoharan (Ogha) to save small insects",
    slide_5: "They use Muhpatti while talking",
    banner_3_text_one: "To follow principles of Bhagwan Mahaveer",
    banner_3_text_two: "To attain Moksh",
    slide_6: "To follow principles of Bhagwan Mahavir's",
    slide_7: "To attain Moksh",
    banner_4_text_one: "They live in Upashray",
    banner_4_text_two: "They do not have any permanent home",
    slide_8: "They live in Upashray",
    slide_9: "They do not have any permanent home",
    banner_5_text_one:
      "They go to different houses for Gochari. They eat whatever they receive in Gochari",
    slide_10:
      "They go to different houses for Gochari. They eat whatever they receive in Gochari",
    banner_6_text_one:
      "Say ' Mathaen Vandami' whenever we see Sadhu - Sadhviji Bhagwant",
    banner_6_text_two:
      "Perform Guruvandan to Sadhu - Sadhviji Bhagwant in Upashray",
    banner_6_text_three: "Request them for Gochari & show them your house",
    slide_11:
      "Say ' Mathaen Vandami' whenever we see Sadhu - Sadhviji Bhagwant",
    slide_12: "Perform Guruvandan to Sadhu - Sadhviji Bhagwant in Upashray",
    slide_13: "Request them for Gochari & show them your house",
  },
  Hindi: {
    home_title1: "जैन साधु कौन है ?",
    home_title2: "जैन साधु कैसे दिखते हैं ?",
    home_title3: "जैन साधु दीक्षा क्यों लेते हैं?",
    home_title4: "जैन साधु कहाँ रहते<br> हैं ? ",
    home_title5: "जैन साधु क्या खाते हैं ?",
    home_title6: " मेरा कर्तव्य क्या है ?",
    home_text1: "जैन साधु कौन है ?",
    home_text2: "जैन साधु कैसे दिखते हैं ?",
    home_text3: "जैन साधु दीक्षा क्यों लेते हैं ?",
    home_text4: "जैन साधु कहाँ रहते हैं ?",
    home_text5: "जैन साधु क्या खाते हैं ?",
    home_text6: " मेरा कर्तव्य क्या है ?",
    banner_1_text_one: "कोई लड़का या पुरुष दीक्षा लेने के बाद साधु कहलाता है",
    banner_1_text_two: "कोई लड़की या स्री दीक्षा लेने के बाद साध्वी कहलाती है ",
    slide_1: "कोई लड़का या पुरुष दीक्षा लेने के बाद साधु कहलाता है",
    slide_2: "कोई लड़की या स्री दीक्षा लेने के बाद साध्वी कहलाती है ",
    banner_2_text_one: " वे सफेद कपड़े पहनते हैं ",
    banner_2_text_two:
      "वे छोटे जीवों की रक्षा के लिए वे रजोहरण (ओघा) का उपयोग करते हैं",
    banner_2_text_three: " वे बोलते समय मुँहपत्तीका उपयोग करते हैं ",
    slide_3: " वे सफेद कपड़े पहनते हैं ",
    slide_4: "वे छोटे जीवों की रक्षा के लिए वे रजोहरण (ओघा) का उपयोग करते हैं",
    slide_5: " वे बोलते समय मुँहपत्तीका उपयोग करते हैं ",
    banner_3_text_one: "भगवान महावीर की आज्ञा का पालन करने के लिए",
    banner_3_text_two: "मोक्ष प्राप्त करने के लिए",
    slide_6: "भगवान महावीर की आज्ञा का पालन करने के लिए",
    slide_7: "मोक्ष प्राप्त करने के लिए",
    banner_4_text_one: "वे उपाश्रय में रहते हैं",
    banner_4_text_two: "उनका कोई भी स्थाई घर होता नहीं ",
    slide_8: "वे उपाश्रय में रहते हैं",
    slide_9: "उनका कोई भी स्थाई घर होता नहीं ",
    banner_5_text_one:
      "वे अलग - अलग घर में गोचरी वहोरने जाते है ! गोचरी में जो भी मिले वे वही वापरते हैं",
    slide_10:
      "वे अलग - अलग घर में गोचरी वहोरने जाते है ! गोचरी में जो भी मिले वे वही वापरते हैं",
    banner_6_text_one:
      "जब भी हमें साधु - साध्वीजी भगवंत दिखें, तब 'मत्थएण  वंदामि' बोलना चाहिए",
    banner_6_text_two:
      "साधु - साध्वीजी भगवंत के उपाश्रय में जाकर गुरुवंदन करना चाहिए ",
    banner_6_text_three:
      "उन्हें गोचरी के लिए विनती करनी चाहिए और अपना घर दिखाना चाहिए",
    slide_11:
      "जब भी हमें साधु - साध्वीजी भगवंत दिखें, तब 'मत्थएण  वंदामि' बोलना चाहिए",
    slide_12: "साधु - साध्वीजी भगवंत के उपाश्रय में जाकर गुरुवंदन करना चाहिए ",
    slide_13: "उन्हें गोचरी के लिए विनती करनी चाहिए और अपना घर दिखाना चाहिए",
  },
  Gujrati: {
    home_title1: "જૈન સાધુ કોણ છે ?",
    home_title2: "જૈન સાધુ કેવા દેખાય છે ?",
    home_title3: "જૈન સાધુ દીક્ષા કેમ લે છે ?",
    home_title4: "જૈન સાધુ ક્યાં રહે છે ?",
    home_title5: "જૈન સાધુ શું ભોજન લે છે ?",
    home_title6: "આપણું કર્તવ્ય શું છે ?",
    home_text1: "જૈન સાધુ કોણ<br>છે ?",
    home_text2: "જૈન સાધુ કેવા<br>દેખાય છે ?",
    home_text3: "જૈન સાધુ દીક્ષા કેમ લે છે ?",
    home_text4: "જૈન સાધુ ક્યાં રહે છે ?",
    home_text5: "જૈન સાધુ શું ભોજન લે છે ?",
    home_text6: "આપણું કર્તવ્ય<br>શું છે ?",
    banner_1_text_one: "એક છોકરો કે પુરુષ દીક્ષા લીધા પછી સાધુ કહેવાય છે",
    banner_1_text_two: "એક છોકરી કે સ્ત્રી દીક્ષા લીધા પછી સાધ્વી કહેવાય છે",
    slide_1: "એક છોકરો કે પુરુષ દીક્ષા લીધા પછી સાધુ કહેવાય છે",
    slide_2: "એક છોકરી કે સ્ત્રી દીક્ષા લીધા પછી સાધ્વી કહેવાય છે",
    banner_2_text_one: "તેઓ સફેદ વસ્ત્રો પહેરે છે",
    banner_2_text_two: "નાના જીવોની રક્ષા માટે રજોહરણ (ઓઘા) નો ઉપયોગ કરે છે",
    banner_2_text_three: "તેઓ બોલતી વખતે મુહપત્તિ નો ઉપયોગ કરે છે",
    slide_3: "તેઓ સફેદ વસ્ત્રો પહેરે છે",
    slide_4: "નાના જીવોની રક્ષા માટે રજોહરણ (ઓઘા) નો ઉપયોગ કરે છે",
    slide_5: "તેઓ બોલતી વખતે મુહપત્તિ નો ઉપયોગ કરે છે",
    banner_3_text_one: "ભગવાન મહાવીરની આજ્ઞાનું પાલન કરવા માટે",
    banner_3_text_two: "મોક્ષ પ્રાપ્તિ માટે (મોક્ષ પ્રાપ્ત કરવા)",
    slide_6: "ભગવાન મહાવીરની આજ્ઞાનું પાલન કરવા માટે",
    slide_7: "મોક્ષ પ્રાપ્તિ માટે (મોક્ષ પ્રાપ્ત કરવા)",
    banner_4_text_one: "તેઓ ઉપાશ્રયમાં રહે છે",
    banner_4_text_two: "તેમનું કોઈ સ્થાયી ઘર હોતું નથી",
    slide_8: "તેઓ ઉપાશ્રયમાં રહે છે",
    slide_9: "તેમનું કોઈ સ્થાયી ઘર હોતું નથી",
    banner_5_text_one:
      "તેઓ અલગ અલગ ઘરે ગોચરી વહોરવા જાય છે. ગોચરીમાં જે પણ મળે તે જ વાપરે છે",
    slide_10:
      "તેઓ અલગ અલગ ઘરે ગોચરી વહોરવા જાય છે. ગોચરીમાં જે પણ મળે તે જ વાપરે છે",
    banner_6_text_one:
      "જ્યારે પણ આપણને સાધુ - સાધ્વીજી ભગવંત દેખાય ત્યારે 'મત્થેણ વંદામિ' બોલવું જોઇએ",
    banner_6_text_two:
      "સાધુ - સાધ્વીજી ભગવંત ને ઉપાશ્રયમાં જઈ ગુરૂવંદન કરવું જોઇએ",
    banner_6_text_three:
      "તેમને ગોચરી માટે વિનંતી કરો અને તેમને તમારું ઘર બતાવો",
    slide_11:
      "જ્યારે પણ આપણને સાધુ - સાધ્વીજી ભગવંત દેખાય ત્યારે 'મત્થેણ વંદામિ' બોલવું જોઇએ",
    slide_12: "સાધુ - સાધ્વીજી ભગવંત ને ઉપાશ્રયમાં જઈ ગુરૂવંદન કરવું જોઇએ",
    slide_13: "તેમને ગોચરી માટે વિનંતી કરો અને તેમને તમારું ઘર બતાવો",
  },
};
