const data = {
  English: {
    link1: "Who am I?",
    link2: "I am a Jain?",
    link3: "What is my duty?",
    whoJain: "Who am I?",
    aboutJain1: "I am a Jeev",
    aboutJain2: "I am a Human",
    IamJain: "I am a Jain?",
    aboutIamJain1: "Jainism is my Religion",
    aboutIamJain2: "Arihants are my Bhagwan",
    aboutIamJain3: "Jain Sadhus are my Guru",
    aboutIamJain4: "I am a Balshravak- Balshravika",
    aboutIamJain5: "I have got most powerful Mantra - Navkar Mantra",
    myDuty: "What is my duty?",
    aboutmyDuty1: "I will follow all the principles of Jainism",
    aboutmyDuty2: "I will do Jin Puja everyday",
    aboutmyDuty3: "I will always bow down to all Guru Bhagwant",
    aboutmyDuty4: "I will be proud of my Jain Religion",
    aboutmyDuty5: "I will respect my Parents",
    aboutmyDuty6: "I will be kind and loving towards all living beings",
  },
  Hindi: {
    link1: "मैं कौन हूँ ?",
    link2: "मैं जैन हूँ ?",
    link3: "मेरा कर्तव्य क्या है ?",
    whoJain: "मैं कौन हूँ ? ",
    aboutJain1: "मैं एक जीव हूँ",
    aboutJain2: "मैं एक मनुष्य हूँ",
    IamJain: "मैं जैन हूँ ?",
    aboutIamJain1: "जैन धर्म मेरा धर्म है",
    aboutIamJain2: "अरिहंत मेरे भगवान हैं",
    aboutIamJain3: "जैन साधु मेरे गुरु हैं",
    aboutIamJain4: "मैं एक बालश्रवक - बालश्राविका हूँ",
    aboutIamJain5: "मुझे दुनिया का सबसे शक्तिशाली मंत्र मिला है - नवकार मंत्र",
    myDuty: "मेरा कर्तव्य क्या है ?",
    aboutmyDuty1: "मैं जैन धर्म के सभी नियमों का पालन करूँगा",
    aboutmyDuty2: "मैं रोज़ जिन पूजा करूँगा",
    aboutmyDuty3: "मैं हमेशा गुरु भगवंतों को वंदन करूँगा",
    aboutmyDuty4: "मैं अपने धर्म पर गर्व रखूँगा",
    aboutmyDuty5: "मैं अपने माता - पिता का आदर करूँगा",
    aboutmyDuty6: "मैं सभी जीवों के प्रति दया और प्रेमभाव रखूँगा",
  },
  Gujrati: {
    link1: "હું કોણ છું?",
    link2: "હું જૈન છું?",
    link3: "મારૂ કર્તવ્ય શું છે?",
    whoJain: "હું કોણ છું?",
    aboutJain1: "હું જીવ છું",
    aboutJain2: "હું એક મનુષ્ય છું",
    IamJain: "હું જૈન છું?",
    aboutIamJain1: "જૈન ધર્મ મારો ધર્મ છે",
    aboutIamJain2: "અરિહંત મારા ભગવાન છે",
    aboutIamJain3: "જૈન સાધુ મારા ગુરૂ છે",
    aboutIamJain4: "હું બાળ શ્રાવક / બાળ શ્રાવિકા છું",
    aboutIamJain5: "મને દુનિયાનો સૌથી શક્તિશાળી મંત્ર મળ્યો છે - નવકાર મંત્ર",
    myDuty: "મારૂ કર્તવ્ય શું છે ?",
    aboutmyDuty1: "હું જૈન ધર્મના તમામ સિદ્ધાંતોનું પાલન કરીશ",
    aboutmyDuty2: "રોજ જિન પૂજા કરવી",
    aboutmyDuty3: "હું હંમેશા બધા ગુરુ ભગવંતોને નમન કરીશ",
    aboutmyDuty4: "મને મારા ધર્મ પર ગર્વ થશે",
    aboutmyDuty5: "માતા - પિતાનો આદર કરવો",
    aboutmyDuty6: "દરેક જીવ પ્રત્યે દયા અને પ્રેમભાવ રાખીશ",
  },
};
